Fix rmdir after zip
hentai-chan/hentai pull request #133
Opened 2021-07-15 13:46 UTC by Shikanime

Unlink only work for file and not directory, since the destination output is always a directory.

2021-07-15 18:38 UTC, hentai-chan commented
Could you please target `hentai-chan:rec-hentai` for your PR? Thanks!

2021-07-15 20:25 UTC, hentai-chan requested changes

2021-07-15 20:25 UTC, hentai-chan commented on src/hentai/hentai.py
> +                dest.rmdir()
From the [docs](https://docs.python.org/3/library/pathlib.html#pathlib.Path.rmdir):
> Remove this directory. The directory must be empty.

I suggest that you use [`shutil.rmtree(dest, ignore_errors=True)`](https://docs.python.org/3/library/shutil.html#shutil.rmtree) instead. On a related note I'd like you to update the `test_download_queue` method in `tests/test_utils.py` by enabling the `zip=True` option to cover this in the unit tests.

2021-07-15 23:34 UTC, hentai-chan commented on src/hentai/hentai.py
> +                dest.rmdir()
Just remembered that this line would have to be modified in the test as well:

```python
# since download deletes dest but not the zip dir, we need 
# to adjust the check against the zip folder, else this fails
self.assertTrue(self.tiny_evil_dir.is_dir())
```

In other words, `f"{self.tiny_evil_dir}.zip"`. But then you'd also need to update the `tearDown` method, so the easiest solution would be to modify the `setUp` method to

```diff
- cls.tiny_evil_dir = Path(str(cls.tiny_evil.id))
+ cls.tiny_evil_dir = Path(f"{cls.tiny_evil.id}.zip")
```
Likewise,

```diff
- Utils.download([self.tiny_evil], progressbar=True)
+ Utils.download([self.tiny_evil], progressbar=True, zip=True)
```

These should be the only changes required to update the test suite.

2021-07-16 11:28 UTC, Shikanime commented on src/hentai/hentai.py
> +                dest.rmdir()
All done, thanks for the review (✿◡‿◡)

2021-07-16 11:38 UTC, Shikanime commented
@hentai-chan  CodeFactor doesn't seem to like the redefinition of `zip', should we skip it or prefix it as `_zip'? This may introduce some minor breaking changes but since the functionality was broken, it seems safe to change it by stealth 😛.

2021-07-16 13:09 UTC, hentai-chan requested changes
Great work! One last request though: change `_zip` to either `zip_` or `zip_dir`. See my second comment in the review for more details.

2021-07-16 13:09 UTC, hentai-chan commented on src/hentai/hentai.py
> -        'ascii': char.rjust(9, ' '),
I love your foresight of removing all trailing white spaces! I'll probably add a `.editorconfig` in my next commits to prevent this from happening again in the future.

2021-07-16 13:09 UTC, hentai-chan commented on src/hentai/hentai.py
> +    def download(self, dest: Path=None, folder: str=None, delay: float=0, _zip: bool=False, progressbar: bool=False) -> None:
According to PEP8 style guidelines, the recommended thing to do would be to add `_` as a suffix and not a prefix (because `_var` is sometimes used to denote a private member or, in case of Python, variables that better be treated as private). Another alternative would be to use `zip_dir` which is a little more descriptive. I'd prefer the second option, but either one is fine in my opinion.

2021-07-16 14:50 UTC, Shikanime commented on src/hentai/hentai.py
> +    def download(self, dest: Path=None, folder: str=None, delay: float=0, _zip: bool=False, progressbar: bool=False) -> None:
Good thing to know, I wasn't sure that in Python（＾∀＾●）ﾉｼ I've seen people use either CamelCase or SnakeCase and in some cases write in one word. I am mostly familiar with functional languages where we usually suffix with `'` as in mathematical notation. I was also looking for a good word, `zip_dir` sounds good!

2021-07-16 15:03 UTC, hentai-chan approved these changes

2021-07-16 15:08 UTC, merged