[ API ] fix API errors WIP
hentai-chan/hentai pull request #163
Opened 2022-09-14 18:32 UTC by ResetXD

I am still working on this.
Though i noticed that with tag searching test case `tag:3d` it doesn't seem to work... it isn't the code issue but i think nhentai removed searching for characters less than 3 and since 3d is `2` it is giving an error

![image](https://user-images.githubusercontent.com/77439837/190232666-e2a04141-5d05-4c6c-8da3-f25050ca682e.png)

second, with `pytest` out of 43 total tests, `9 failed, 34 passed` but when i changed the `tag:3d` to say `tag:3dlive` then the testcases for tag searching works

@hentai-chan thoughts?

currently i am making a temporary fix with changing query parameter into a string and then concatenating the string to make URL so `payload = {'query': query, 'page': page, 'sort': sort.value}` becomes `payload = f"?query={query}&page={page}&sort={sort.value}"` 
this is just a temporary solution and if everything works i will make a proper function to have something like this...

2022-09-14 18:44 UTC, ResetXD commented
```py
def test_random_hentai(self):
        random_hentai = Utils.get_random_hentai()
        response = requests.get(random_hentai.url)
        self.assertEqual(response.status_code, 200, msg=f"Failing URL: {response.url} (status code: {response.status_code})")
```
As a test won't work since `requests.get` will not get 200, ever

2022-09-14 19:02 UTC, ResetXD commented
Oh  the test should have passed since the testing data is old `Tag(i[29 chars]shindol', url='https://nhentai.net/artist/shindol/', count=279)` | `Tag(i[29 chars]shindol', url='https://nhentai.net/artist/shindol/', count=291)`

though i still have no idea about `test_cli` since i have never worked with shlex

2022-09-14 19:14 UTC, hentai-chan commented
> Though i noticed that with tag searching test case tag:3d it doesn't seem to work... it isn't the code issue but i think nhentai removed searching for characters less than 3 and since 3d is 2 it is giving an error

If this is true (which I will check later during the weekend when I have time) you should consider adding a check in any methods that use this parameter in this fashion add

```python
if (len(query)<3):
    raise ArgumentError("todo: add descriptive error message here")
```

Change the sample query in the unit tests to something else, but try to look for a tag that yields few results to decrease server load since unit tests are run fairly frequently during development.

> As a test won't work since requests.get will not get 200, ever

Make corrections to the code as you see fit at the moment, we can discuss your changes during the code review later.

2022-09-14 19:17 UTC, ResetXD commented
> ```python
> if (len(query)<3):
>     raise ArgumentError("todo: add descriptive error message here")
> ```

Alright i will look into that as well

> Change the sample query in the unit tests to something else, but try to look for a tag that yields few results to decrease server load since unit tests are run fairly frequently during development.

I found `3dlive` to be working good enough

2022-09-14 19:17 UTC, hentai-chan commented
A note on branching policy: contributors should always target the development branch `rec-hentai`, not `master`. We do this to make some final tests in order to ensure that the next release works as intended.

2022-09-14 19:18 UTC, ResetXD commented
oh, i was looking for `dev-api` branch but couldn't find one so i just targeted master.

2022-09-14 19:32 UTC, hentai-chan commented on src/hentai/hentai.py
> +        with handler.get(urljoin(Hentai.HOME, '/api/galleries/search'+payload)) as response:
strings should never be concatenated, see also: <https://pakstech.com/blog/python-build-urls/> for an example of how to build a URL correctly, if you see yourself needing an auxiliary method in `hentai.py`, consider implementing a `__build_api` in the `RequestHandler` class

2022-09-14 19:34 UTC, ResetXD commented on src/hentai/hentai.py
> +        with handler.get(urljoin(Hentai.HOME, '/api/galleries/search'+payload)) as response:
oh its alright, its just a temporary solution, later i plan on using `urllib.urlencode`

2022-09-14 19:37 UTC, ResetXD commented
On checking the Tag error again, i can conclude that it isnt about len but it is something completely different that i don't seem to understand, for example `tag:!`  shows error but `tag:@` doesn't

Do you know what is going on?

2022-09-14 19:39 UTC, hentai-chan commented on src/hentai/hentai.py
> +        with handler.get(urljoin(Hentai.HOME, '/api/galleries/search'+payload)) as response:
alright I will let you do your thing until you request a code review, in the meantime I will be busy working on other projects, but you can still ask me questions (if you have any). I usually respond in a reasonable timeframe.

2022-09-14 19:47 UTC, hentai-chan commented
> Do you know what is going on?

Just a wild guess but try to update the `177013.json` test reference file in the `tests` directory. On your branch, open a terminal session, import the `hentai` module and run

```python
> from hentai import Hentai, Option
> doujin = Hentai(177013)
> doujin.export(filename=Path("tests").joinpath("f{doujin.id}.json"), options=[Option.Raw])
```

2022-09-14 20:04 UTC, ResetXD commented
`4 failed, 40 passed in 91.19s (0:01:31)`

4 failed are `tests/test_cli.py::TestHentaiCLI::test_cli_download` `tests/test_cli.py::TestHentaiCLI::test_cli_log` `tests/test_cli.py::TestHentaiCLI::test_cli_preview` `tests/test_hentai.py::TestHentai::test_num_favorites_edge_case` of which i have no idea

2022-09-14 20:08 UTC, ResetXD commented
also why is `json.dump([doujin.json for doujin in iterable], file_handler)` storing it as a `list`?
Thats just gonna make all the tests fail... i had to remove the dict from the list since API doesn't return list

2022-09-14 20:21 UTC, ResetXD commented
`3 failed, 41 passed in 86.30s (0:01:26)`

with that i think that's all i can do, i need some code review and suggestions for test_cli.py by you now

2022-09-16 13:17 UTC, ResetXD commented
I checked everything and couldn't find anything else to improve

2022-09-17 09:24 UTC, ResetXD commented
today i will get code review?

<img src="https://cdn.discordapp.com/emojis/1017513020626321479.webp?size=96&quality=lossless">

2022-09-17 22:04 UTC, hentai-chan commented
> today i will get code review?

I will make the review sometime around Sunday. There are a few things that have been on my mind for a quite a while now that I may want to test out myself (for which I would open up a separate branch), and even in the best-case scenario I would still have to update the docs on my website and stress-test the `rec-hentai` branch to ensure everything works perfectly, though this in and of itself doesn't take much time.

I am a little hesitant whether I will consider your patch a permanent addition to the library code or a temporary fix until nhentai devs work out a proper solution for the REST API (see also: #155). We don't know for certain how long your workaround is going to stay functional because it's quite a hack, to be honest. So, in the event I decide to add new features to this library reverting back the current version (`3.2.10`) will prove to be more difficult (but not impossible) in case nhentai does decide to implement  OAuth2 authentication. Perhaps that's just a bullet I have to bite in the moment.

But, depending on your reliability, there are a few things I could use your help with in the future which is something we could discuss in private another time on Discord if you are interested, though these only involve long term plans with the library and the direction it's heading to.

2022-09-18 05:46 UTC, ResetXD commented
Hit me up on discord `resetxd#8278`

2022-09-22 18:13 UTC, ResetXD commented
about this method `browse_homepage`, do we really need a set as a return type and make our work harder? won't list be a better option here?

```py
    @staticmethod
    def browse_homepage(start_page: int, end_page: int, handler: RequestHandler=RequestHandler(), progressbar: bool=False) -> Set[Hentai]:
        """
        Return a list of `Hentai` objects that are currently featured on the homepage
        in range of `[start_page, end_page]`. Each page contains as much as 25 results.
        Enable `progressbar` for status feedback in terminal applications.
        """
        if start_page > end_page:
            raise ValueError(f"{COLORS['red']}{os.strerror(errno.EINVAL)}: start_page={start_page} <= {end_page}=end_page is False{COLORS['reset']}")
        data = set()
        for page in tqdm(**_progressbar_options(range(start_page, end_page+1), 'Browse', 'page', disable=progressbar)):
            with handler.get(urljoin(Hentai.HOME, 'api/galleries/all' + "?" + urlencode({'page': page})) ) as response:
                for raw_json in response.json()['result']:
                    data.add(Hentai(json=raw_json))
        return data
```

changes to

```py
    @staticmethod
    def browse_homepage(start_page: int, end_page: int, handler: RequestHandler=RequestHandler(), progressbar: bool=False) -> Set[Hentai]:
        """
        Return a list of `Hentai` objects that are currently featured on the homepage
        in range of `[start_page, end_page]`. Each page contains as much as 25 results.
        Enable `progressbar` for status feedback in terminal applications.
        """
        if start_page > end_page:
            raise ValueError(f"{COLORS['red']}{os.strerror(errno.EINVAL)}: start_page={start_page} <= {end_page}=end_page is False{COLORS['reset']}")
        data = list()
        for page in tqdm(**_progressbar_options(range(start_page, end_page+1), 'Browse', 'page', disable=progressbar)):
            with handler.get(urljoin(Hentai.HOME, 'api/galleries/all' + "?" + urlencode({'page': page})) ) as response:
                for raw_json in response.json()['result']:
                    data.append(Hentai(json=raw_json))
        return data
```

2022-09-25 22:53 UTC, hentai-chan requested changes
Sorry for the late review, I am really busy at the moment but I finally got around to review your pull request :) Overall good work! I remarked a few things that needs to be work, don't worry about the CLI related tests I will take care of them once your branch has merged.

2022-09-25 22:53 UTC, hentai-chan commented on src/hentai/hentai.py
> +        elif isinstance(other, str):
Condition should close with `else` not `elif` (which implies an unhandled third branch); we use duck typing to push the second type (`str`), which in my opinion is good enough. So, here are two suggestions:

```python
def __eq__(self, other: Union[Tag, str]) -> bool:
    """
    Compare for equality by `Tag` or a tag's name.

    Example
    -------

    ```
    # write example no. 1 here
    # then one more example for comparison by name 
    ```
    """
    return self.id == other.id if isinstance(other, Tag) else self.name == other
```

You can check the other doc strings to learn how to write example code. Bear in mind that a running theme of this library is to use doujin 177013 and its associated properties as a primary example.

2022-09-25 22:53 UTC, hentai-chan commented on src/hentai/hentai.py
> +    _updated_client = "https://translate.google.com/translate?sl=vi&tl=en&hl=vi&u={0}&client=webapp"
It would be better to rename this field to `_alt_url` since it's an alternative URL representation. A client in this context means something different altogether.

2022-09-25 22:53 UTC, hentai-chan commented on src/hentai/hentai.py
> +                 updated_client: str=_updated_client) -> None:
In the spirit of the aforementioned remark it would make sense to rename this parameter as well. Maybe something like `enable_alt_url`? This should also be a boolean parameter (with a default value of `False` in `RequestHandler` and `True` in `Hentai`). If set to `True`, then

```python
self._alt_url = if enable_alt_client f"https://translate.google.com/translate?sl=vi&tl=en&hl=vi&u={0}&client=webapp" else "{0}"
```

The reason why it should default to `False` in `RequestHandler` is that this way it doesn't modify existing code that rely on this abstraction. `Hentai`, on the other hand, inherits from `RequestHandler` and should turn it on by default for the next version in order to make this library work again. If this sounds confusing to you let me know in the comments and I will elaborate on the difference a little bit more.

2022-09-25 22:53 UTC, hentai-chan commented on src/hentai/hentai.py
> +        Return a set of `Hentai` objects that are currently featured on the homepage
Good catch!

2022-09-25 22:53 UTC, hentai-chan commented on src/hentai/hentai.py
> +            with handler.get(urljoin(Hentai.HOME, 'api/galleries/all' + "?" + urlencode({'page': page})) ) as response:
Use f-strings instead:

```diff 
- with handler.get(urljoin(Hentai.HOME, 'api/galleries/all' + "?" + urlencode({'page': page})) ) as response:
+ with handler.get(urljoin(Hentai.HOME, f"api/galleries/all?{urlencode({'page': page}))}" ) as response: 
```

2022-09-25 22:53 UTC, hentai-chan commented on src/hentai/hentai.py
> +        with handler.get(urljoin(Hentai.HOME, 'api/galleries/search'+ "?" + urlencode({'query': query, 'page': page, 'sort': sort.value}))) as response:
Use f-strings instead

2022-09-25 22:53 UTC, hentai-chan commented on src/hentai/hentai.py
> +        with handler.get(urljoin(Hentai.HOME, "api/galleries/tagged" + "?" + urlencode({'tag_id': id_, 'page': page, 'sort': sort.value}))) as response:
Use f-strings instead

2022-09-25 22:53 UTC, hentai-chan commented on tests/test_utils.py
> +        self.assertEqual(type(random_hentai.json), dict, msg=f"Failing URL: {random_hentai.url} (possibility: doesn't exists(?) or blocked by Cloudflare)")
Change of language suggestion:

```
f"Failing URL: {random_hentai.url} (resource might not exist or is blocked by Cloudflare protection)")
```

2022-09-25 22:53 UTC, hentai-chan commented on src/hentai/hentai.py
> +    __slots__ = ['timeout', 'total', 'status_forcelist', 'backoff_factor', 'user_agent', 'proxies', "updated_client"]
Should be renamed as well (though this might go without saying but it's better to have this remark for the sake of completeness) :)

2022-09-25 23:06 UTC, hentai-chan commented
> about this method `browse_homepage`, do we really need a set as a return type and make our work harder? won't list be a better option here?

Believe it or not, the API used to return a list of `Hentai` objects in the past. I changed it to a set for the following reasons:

- a **set** is faster if you care about querying the data structure for checking existence of other objects
- **sets** also only contain _unique_ values which was important to me to emphasize here
- **lists** are subscriptable and sortable (as opposed to sets though sets are sorted by insertion order, so we still have a correctly sorted collection by virtue of the set initialization)

The only "downside" is that the result of this function is not subscriptable which can be easily worked around by converting the result to list with the `list()` method, so I am forcing the end user to make a conscious decision in that regard: do you need access by index? If so convert it to list, else reap the benefits of the set data structure

2022-09-26 11:25 UTC, ResetXD commented
@hentai-chan 
`== 44 passed in 171.84s (0:02:51) == `

all the test passes, (maybe the CLI test failed because i was having py2 and py3 in the same environment(?) )
This commit has all the requested changes though i might have overlooked some(?)

2022-11-22 18:09 UTC, ResetXD commented
Hey hentai-chan,
Are we still working on this update? This updated was required for this library to function properly once again. 
Sorry i had gotten myself into other IRL stuff and wasn't able to update or work on this PR at all. Is there something i missed and need work on again?

I am really sorry for such a delayed reponse.

regards,
resetxd

2022-12-30 21:10 UTC, hentai-chan commented
Sorry for the late reply, but I have actually decided to no longer go forward with this solution (which was more of a hack anyway) since there already exists a documented solution for cloudflare-protected sites to disable clients from accessing the site through a Google-translate link: 

https://community.cloudflare.com/t/prevent-unwanted-visitors-from-using-google-translate-to-access-your-site/197923

Thus it would only be a matter of time for the web administrator to catch on to this change if they keep an eye open on their API usage, which is not unlikely considering this project and discussions revolving around it are taking place on a public forum.

2022-12-30 21:24 UTC, ResetXD commented
ah that seems like a good decision!
if they can disable this as well then there really isn't something we can do (at least in our knowledge).

maybe you have looked for another workaround?

well anyways i hope you can look for something to revive the NSFW community up again.
you may close the PR yourself after you have something to say about this.

2022-12-30 21:30 UTC, closed without merging

2022-12-30 21:36 UTC, hentai-chan commented
You may continue your work in this sibling repository as a temporary workaround:

https://github.com/AlexandreSenpai/NHentai-API/pull/43

I can try one more time to get in touch with the web admin at nhentai in order to find a solution that works for both sides, but past efforts have made me doubt that I will receive a response.